### ISSUE TITLE
ReferenceError: window is not defined in Nuxt3

### ISSUE THREAD

**Issue by johnpc** [lakb248/vue-pull-refresh#21]
```
ReferenceError: window is not defined                                                                                                        5:05:33 PM
    at /home/user/repo/vue-app/node_modules/vue-pull-refresh/dist/vue-pull-refresh.min.js:1:14451
    at /home/user/repo/vue-app/node_modules/vue-pull-refresh/dist/vue-pull-refresh.min.js:1:14383
    at n.exports (/home/user/repo/vue-app/node_modules/vue-pull-refresh/dist/vue-pull-refresh.min.js:1:14801)
    at Object.<anonymous> (/home/user/repo/vue-app/node_modules/vue-pull-refresh/dist/vue-pull-refresh.min.js:1:15257)
    at t (/home/user/repo/vue-app/node_modules/vue-pull-refresh/dist/vue-pull-refresh.min.js:1:332)
    at Object.<anonymous> (/home/user/repo/vue-app/node_modules/vue-pull-refresh/dist/vue-pull-refresh.min.js:1:750)
    at t (/home/user/repo/vue-app/node_modules/vue-pull-refresh/dist/vue-pull-refresh.min.js:1:332)
    at Object.<anonymous> (/home/user/repo/vue-app/node_modules/vue-pull-refresh/dist/vue-pull-refresh.min.js:1:4067)
    at t (/home/user/repo/vue-app/node_modules/vue-pull-refresh/dist/vue-pull-refresh.min.js:1:332)
    at /home/user/repo/vue-app/node_modules/vue-pull-refresh/dist/vue-pull-refresh.min.js:1:715
```

**Comment by PhenomEY** [comment]
use `<client-only>`
